apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf-external
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    #Config to redirect http to https
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [api]
      [api.statistics]
        recentErrors = 10

    [kubernetes]
      # Only create ingresses where the object has traffic-type: external label
      labelselector = "traffic-type=external"

    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"

    [ping]
      entryPoint = "http"

    [accessLog]

    [consul]
      endpoint = "consul-traefik.kube-system.svc:8500"
      watch = true
      prefix = "traefik-external"

    [acme]
      entryPoint = "https"
      email = "amerenda89@gmail.com"
      storage = "traefik-external-certificates/acme/account"
      acmeLogging = true
      OnHostRule = true
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [acme.dnsChallenge]
        provider = "digitalocean"
      [[acme.domains]]
        main = "*.cloud.stormhold.net"
      [[acme.domains]]
        main = "*.cloud.amer.dev"
