apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf-internal
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"
    # Do not verify backend certificates (use https backends)
    #Config to redirect http to https
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [consul]
      endpoint = "consul-traefik.kube-system.svc:8500"
      watch = true
      prefix = "traefik-internal"

    [api]
      address = ":8080"

    [kubernetes]

    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"

    [ping]
    entryPoint = "http"

    [acme]
      entryPoint = "https"
      email = "amerenda89@gmail.com"
      storage = "traefik-internal-certificates/acme/account"
      acmeLogging = true
      OnHostRule = true
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [acme.dnsChallenge]
        provider = "digitalocean"
      [[acme.domains]]
        main = "*.home.stormhold.net"
      [[acme.domains]]
        main = "*.home.amer.dev"
