---
apiVersion: batch/v1
kind: Job
metadata:
  name: traefik-kv-store
  namespace: kube-system
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: traefik-kv-store
    spec:
      containers:
      - name: storeconfig
        image: traefik:v1.6
        imagePullPolicy: IfNotPresent
        args: [ "storeconfig", "--configfile", "/config/traefik.toml" ]
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: traefik-conf-external
          items:
          - key: traefik-config
            path: traefik.toml
